### ISSUE TITLE
Potential Code Issue

### ISSUE THREAD

**Issue by lliangthomas** [m-kruse98/SplatPose#2] opened 2024-06-03 15:53 UTC
Hi there,

Is there a potential issue with the code here: https://github.com/m-kruse98/SplatPose/blob/main/train_and_render.py#L174 ?

I received an error that gt_masks should contain {0, 1} or {-1, 1} whereas it contains {0, 255}. 

I fixed this with gt_mask[gt_mask == 255] = 1. Is this an error on my part?

**Comment by m-kruse98** [comment] 2024-06-03 19:52
Hey and thanks for the interest,

I tried to reproduce the same error, however when printing the gt_mask values, they were in {0, 1}. This could be possibly due to different library versions (PyTorch, torchvision or NumPy) or different operating systems.

Your fix is indeed correct for your case.

The next days, I will look into cleaning up the code a bit, since the data loading is currently very over-complicated due to the merged codebases (we load the mask in utils_pose_est.py as a FloatTensor and convert it several times, which is not really needed).

Maybe this will then prevent future issues.

All the best,
Mathis

**Closed as completed** 2024-06-03 20:31 UTC
